# theme: jekyll-theme-tactile
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#theme: minima
# theme: jekyll-theme-hacker
# remote_theme: pages-themes/modernist@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/primer@v0.2.0
remote_theme: just-the-docs/just-the-docs

#color_scheme: uj-light

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Prognisk]
description: [Programowanie niskopoziomowe]
#show_downloads: [false]

nav_external_links:
  - title: Strona wykładu
    url: https://ww2.ii.uj.edu.pl/~kapela/pn/
  - title: Biblioteka ASM64_IO
    url: https://tomasz-kapela.github.io/asm64_io/
    hide_icon: true # set to true to hide the external link icon - defaults to false


url: https://tomasz-kapela.github.io # the base hostname & protocol for your site
#url: https://ww2.ii.uj.edu.pl # the base hostname & protocol for your site

#baseurl: /my-webpage # the subpath of your site, e.g. /blog/
baseurl: /prognisk/  # the subpath of your site, e.g. /blog/
last_updated: true # set to true if you want to display last updated in the footer
impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# code highlighter theme
highlight_theme_light: github   # https://github.com/jwarby/jekyll-pygments-themes
highlight_theme_dark: native    # https://github.com/jwarby/jekyll-pygments-themes


